Module5 task1
htmlacademy-nodejs/194522-buy-and-sell-3 pull request #12
Opened 2021-01-16 17:09 UTC by dm-gthb

2021-01-17 14:51 UTC, LordotU requested changes

2021-01-17 14:51 UTC, LordotU commented on schema.sql
> +  title varchar(255) NOT NULL,
Кажется, не хватает индекса для поля, т.к. по нему будет происходить поиск

2021-01-22 17:03 UTC, dm-gthb commented on schema.sql
> +  title varchar(255) NOT NULL,
добавил [b648a1c](https://github.com/htmlacademy-nodejs/194522-buy-and-sell-3/pull/12/commits/b648a1ce95ca9361cb18a780a1994489c97a3f8c)

2021-01-29 08:53 UTC, LordotU approved these changes

2021-01-29 08:53 UTC, merged